export const NAVIGATION_AUTH_SUCCESS = 'NAVIGATION_AUTH_SUCCESS';
export const NAVIGATION_LOGOUT = 'NAVIGATION_LOGOUT';

export const AUTH_INITIAL = 'AUTH_INITIAL';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
