export const NAVIGATION_ROOT = 'NAVIGATION_ROOT';
export const NAVIGATION_MAIN = 'NAVIGATION_MAIN';
export const NAVIGATION_AUTH = 'NAVIGATION_AUTH';
export const NAVIGATION_MODULE = 'NAVIGATION_MODULE';

export const AUTH_INITIAL = 'AUTH_INITIAL';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT_INITIAL = 'AUTH_LOGOUT_INITIAL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
